### ISSUE TITLE
Basic example with appendix

### ISSUE THREAD

**Issue by peekxc** [flaribbit/numbly#1]
Can this plugin/extension help me add an appendix after the references for my paper? 

I tried installing this extension but it didn't seem to do anything...

I'm using the IEEE format, if that matters

**Comment by flaribbit** [comment]
> I tried installing this extension but it didn't seem to do anything...

I tested it with the official charged-ieee template and reproduced the issue you mentioned.

After diving into it, I find that [it used a custom show rule on headings](https://github.com/typst/templates/blob/main/charged-ieee/lib.typ#L91), which will **overwrite** the `#set heading(numbering: xxx)` rule.

I think the easiest way is to just write it manually.

![image](https://github.com/user-attachments/assets/45a1942f-c37a-4786-a720-64df6ce1ceed)


```typst
#heading(numbering: none)[Appendix A\
Title of the 1st appendix]
```

**Comment by peekxc** [comment]
Ahh that worked, thanks @flaribbit. Makes sense the template would interfere here. 

Do you by chance know how to move the appendix past the references?

**Comment by peekxc** [comment]
Ahh, nvm, I found out I just have to supply `none` to `ieee.with` function and just manually add the appendix after.

Thanks for the help!
