### ISSUE TITLE
Can we change numbly behavior with a flag?

### ISSUE THREAD

**Issue by Doom4535** [flaribbit/numbly#3]
Is it possible to add a behavior type flag that numbly can pickup to change the behavior (for things such as appendixes?) something along the lines of:

```typst
= Conclusions
My conclusions

= Matlab files #:Appendix: #t
== ustep.m #:Appendix: #t
#let text = read("matlab/ustep.m")
#raw(text, lang: "matlab")
```

**Comment by flaribbit** [comment]
Hello, put flag in headings seems strange to me, I would suggest something like this:

```typst
#import "@preview/numbly:0.1.0": numbly
#set heading(numbering: "1.")
#outline(indent: 2em)
= Introduction
= Related Work
= Proposed Method
= Experiments
= Conclusions

#set heading(numbering: numbly("Appendix {1:A}.", "File {1:A}.{2}.")) // change numbering format of headings
#counter(heading).update(0) // reset heading counter

= Matlab files
== ustep.m
== main.m
```

You will get
![image](https://github.com/user-attachments/assets/1285398f-044e-4ca6-8742-122f193ea700)

**Comment by flaribbit** [comment]
If you have more complex requirements, you can refer to

https://typst-doc-cn.github.io/guide/FAQ/heading-various-format.html

https://typst-doc-cn.github.io/guide/FAQ/variant-heading.html

**Comment by Doom4535** [comment]
Awesome, your examples do exactly what I need, thank you.
