### ISSUE TITLE
Underlines broken between numbering and heading

### ISSUE THREAD

**Issue by ffalcon31415** [flaribbit/numbly#4]
Thanks for this great plugin.

I noticed that when I underline my heading it doesn't behave as expected (by me, in any case). 

```
#import "@preview/numbly:0.1.0": numbly

#set heading(numbering: numbly(
  "{1:I}", 
))


#show heading.where(level:1): it => {
  underline(it)
}

= Heading
```

This results in:

![ClipboardImage](https://github.com/user-attachments/assets/15ff667b-9478-44a0-9b5d-2bb63638381d)

I do not want the gap in underline between the numbering and the heading.

Any help would be appreciated!

**Comment by flaribbit** [comment]
Typst puts an `h(0.3em)` between *numbering* and *body* in the default show rule of headings (see https://github.com/typst/typst/blob/33a035ee0d9f12bc858e9a0cd37942eda1693798/crates/typst-library/src/model/heading.rs#L219). The underline is not drawn on `h` element.

To fix it, we can replace that `h` with a simple space.

```typst
#import "@preview/numbly:0.1.0": numbly

#set heading(numbering: numbly(
  "{1:I}", 
))


#show heading.where(level:1): it => {
  show h.where(amount: 0.3em): [ ]
  underline(it)
}

= Heading
```

![image](https://github.com/user-attachments/assets/86e4799d-16d2-433c-8ee4-6303c8abfd5d)

**Comment by ffalcon31415** [comment]
Thank you so much for solving my issue.
